service: mailchiamp-serverless-email-notification 
custom:
  stage: "${opt:stage, self:provider.stage}"

provider:
  name: aws
  runtime: nodejs4.3
  environment: ${file(env.yml):${self:custom.stage}}
  memorySize: 512 # optional, default is 1024


functions:
  mail:
    handler: handler.send
    description: Send email via Mailchimp API
    memorySize: 256
    timeout: 10
    events:
      - http:
          method: post
          path: send
          cors: true
          private: true
          response:
          integration: lambda

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Description: ${self:provider.stage} - email service

plugins:
  - serverless-offline